### ISSUE TITLE
Delete treshold is not respected if move quickly

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [letsar/flutter_slidable#230]
Version: 1.0.0-dev.6

https://user-images.githubusercontent.com/3918999/126668043-440b04ca-c423-45c7-b20e-919ed441f674.mov

described here: https://github.com/letsar/flutter_slidable/issues/223

**Comment by letsar** [comment]
I cannot reproduce. Can you share some code?

**Comment by vytautas-pranskunas-** [comment]
Sure

```
new Slidable(
      key: Key(notification.id),
      endActionPane: ActionPane(
        motion: const DrawerMotion(),
        extentRatio: 0.25,
        dismissible: DismissiblePane(
          onDismissed: () => _controller.onSwipeDetelete(notification.id, index),
          closeOnCancel: true,
        ),
        children: [
          SlidableAction(
            icon: Icons.delete,
            backgroundColor: CustomColors.imperialRed,
            onPressed: (context) {},
          ),
        ],
      ),
      child: notificationView,
```

**Comment by letsar** [comment]
Can you send me a complete sample I would just have to run to reproduce the issue?

**Comment by vytautas-pranskunas-** [comment]
I cannot because its big peace :) but you see it in video :(

**Comment by letsar** [comment]
Can't you make a basic code sample that reproduce the issue? Sorry but without something to reproduce it, I can't fix it.

**Comment by vytautas-pranskunas-** [comment]
I understand how it works. But to make reproducable example it might take long because not sure what cuases it. 
This" https://github.com/letsar/flutter_slidable/issues/229 might be impacted by MobX but empty clicks should not efeect that.
This, what you see in video, it basically empty code as I gave you. There is nothing more.... It is not reproducable every time. Just try to play with it... Move it slowly long way, then couple of times faster but not long way... I really was not doing anything speciall, I just migrated the code to latest version and noticed that after few attempts to delete.

If neither works - maybe after app release (aprox 2-4 weeks) I will try to do reprodcuable code :) but please try first

**Comment by letsar** [comment]
I've just published a fix for an animation issue. Did it also resolve your issue?

**Comment by vytautas-pranskunas-** [comment]
I will check. Have you been able to reproduce it?

**Comment by letsar** [comment]
No I didn't really reproduced this issue nor the 229, but maybe it resolved what you experienced.

**Comment by vytautas-pranskunas-** [comment]
Yes it is fixed now.

**Comment by marcio-ota** [comment]
The problem persist on 1.1.0
When SlidableAction is opened and move, a little bit, quickly

**Comment by buvtopcc** [comment]
I encountered the same problem, through the modification of the source code to [solve。
<img width="681" alt="image" src="https://user-images.githubusercontent.com/12746465/215751709-dc13911c-dc33-4cca-a052-ada428d7affd.png">
